ALTER TABLE users
    ADD COLUMN IF NOT EXISTS image_url VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS shop_id BIGINT;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS shop_code VARCHAR(255);